# Generated by Django 4.2.7 on 2023-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wonder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('creator', models.CharField(blank=True, max_length=25)),
                ('created', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('current_status', models.CharField(choices=[('e', 'Exists'), ('d', 'Destroyed')], max_length=25)),
            ],
        ),
    ]
